# склейка shaders/sdf/*.wgsl по именам в один модуль (порядок = зависимости)
file(GLOB _parts "${SRCDIR}/*.wgsl")
list(SORT _parts)
set(_out "#pragma once\n// Собрано из shaders/sdf/*.wgsl. Не править руками.\nstatic const char *SDF_WGSL = R\"SDF(\n")
foreach(f IN LISTS _parts)
  file(READ "${f}" _c)
  if(_c MATCHES "\\)SDF\"")
    message(FATAL_ERROR "в ${f} есть )SDF\" — смени разделитель")
  endif()
  string(APPEND _out "${_c}\n")
endforeach()
string(APPEND _out ")SDF\";\n")
file(WRITE "${DST}" "${_out}")
