# склейка shaders/sdf/*.wgsl по именам в один модуль (порядок = зависимости)
file(GLOB _parts "${SRCDIR}/sdf/*.wgsl")
list(SORT _parts)
set(_out "#pragma once\n// Собрано из shaders/sdf/*.wgsl. Не править руками.\nstatic const char *SDF_WGSL __attribute__((unused)) = R\"SDF(\n")
foreach(f IN LISTS _parts)
  file(READ "${f}" _c)
  if(_c MATCHES "\\)SDF\"")
    message(FATAL_ERROR "в ${f} есть )SDF\" — смени разделитель")
  endif()
  string(APPEND _out "${_c}\n")
endforeach()
string(APPEND _out ")SDF\";\n")
# печка неба: 00_atmo — общий префикс, 10/20/30/40 — модули (их wc_* 1:1)
file(READ "${SRCDIR}/sky/00_atmo.wgsl" _atmo)
foreach(n TRANS MS VIEW AMB)
  if(n STREQUAL "TRANS")
    set(_f "${SRCDIR}/sky/10_trans.wgsl")
  elseif(n STREQUAL "MS")
    set(_f "${SRCDIR}/sky/20_ms.wgsl")
  elseif(n STREQUAL "VIEW")
    set(_f "${SRCDIR}/sky/30_view.wgsl")
  else()
    set(_f "${SRCDIR}/sky/40_amb.wgsl")
  endif()
  file(READ "${_f}" _c)
  string(APPEND _out "static const char *SKY_${n}_WGSL __attribute__((unused)) = R\"SDF(\n${_atmo}\n${_c})SDF\";\n")
endforeach()
file(WRITE "${DST}" "${_out}")
